py_library(
    name="lib_files",
    srcs=[
        "file_diff.py",
        "file_reader.py",
        "file_compare.py",
        "line_compare.py",
        "utilities.py",
    ],
    visibility=["//main:__pkg__", "//test:__pkg__"],
)
